avoid: ejectable media cannot use virtio type
Minor adjustment to avoid the following error with an up to date version
of libvirt:

```
libvirt.libvirtError: unsupported configuration: disk type 'virtio' of 'vdc' does not support ejectable media
```

See: https://marc.info/?l=libvir-list&m=154929531226510&w=2